### ISSUE TITLE
Что это за магические функции и числа в Generator.h?

### ISSUE THREAD

**Issue by Kalashnikov-Ivan** [NarakattiTirumpo/ConsoleTetris#1]
Что это за загадочный код?
```cpp
unsigned long long TetrisRand()
{
	unsigned long long Rd; //Contain garbage
	
	Rd += 123456791 * __rdtsc();
	Rd += _rotl64(123456791 * Rd, 5);
	Rd += _rotl64(Rd, 7);
	Rd += _rotl64(Rd, 11);
	Rd ^= _rotl64(Rd * __rdtsc(), 23);

	return Rd;
}
```

**Comment by NarakattiTirumpo** [comment]
Немного изменю ответ из гиста, если кто еще будет спрашивать.
Перемешиваем мусорную переменную определенным образом со значеним счетчика тактов используя кручение бит в регистре и возвращаем значение.
Гист потру немного. Если долго не отвечаю, напиши туда - смело и  без сомнений!
