### ISSUE TITLE
Почему коды клавиш в 16-ричной форме?

### ISSUE THREAD

**Issue by Kalashnikov-Ivan** [NarakattiTirumpo/ConsoleTetris#2]
Почему коды клавиш в 16-ричной форме? Разве ASCII не представлены в 10-ричной? Чем оправдывается такая форма записи (мне интересно :3)?

```cpp
enum BOTTONS { SPACE_BUTTON = 0x20, D_BUTTON = 0x44, A_BUTTON = 0x41, W_BUTTON = 0x57, S_BUTTON = 0x53, R_BUTTON = 0x52 };
```

**Comment by NarakattiTirumpo** [comment]
https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by Kalashnikov-Ivan** [comment]
О! Полезная вещь. Раньше гуглил, но не натыкался. Спасибо!
