### ISSUE TITLE
typedef'ы

### ISSUE THREAD

**Issue by Kalashnikov-Ivan** [NarakattiTirumpo/ConsoleTetris#3]
```cpp
typedef unsigned char uint8;
typedef long int int32;
```
Кстати, чтобы не typdef'ить самому типы к uint8, int8, int16 и тд, можно подключить специальный заголовочник `<cstdint>` (или stdint.h для Си), где всё это уже содержится и есть другие полезные макросы для тех или иных значений типов (UINT8_MAX и др)
https://en.cppreference.com/w/cpp/header/cstdint

**Comment by NarakattiTirumpo** [comment]
Это старая привычка, спасибо за критику.
